spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# db source url
spring.datasource.url=jdbc:mysql://localhost:3306/test

# db response name
spring.datasource.username=newuser

# db response password
spring.datasource.password=dkssud123

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

application.name=Capstone Analytics Reporting
key.file.location=${user.dir}/src/main/resources/analytics/capstone-384211-b0839a23314c.json
view.id=288774560